version: '3.9'
services:
  backend:
    build: .
    container_name: ambassador-microservice
    ports:
      - 8002:3000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - ambassador
      - users
  db:
    image: mysql:8
    container_name: ambassador-db
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - ambassador
  redis:
    image: redis
    container_name: nest-ambassador-redis
    ports:
      - 6379:6379
    networks:
      - ambassador

networks:
  ambassador:
    name: ambassador
  users:
    external:
      name: users
