version: '3.9'
services:
  backend:
    build: .
    command: 'npm run start:dev'
    container_name: admin-microservice
    ports:
      - 8001:3000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - admin
      - users
  db:
    image: mysql:8
    container_name: admin-db
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - admin

  consumer:
    build: .
    command: 'npm run consume'
    container_name: admin-consumer
    depends_on:
      - db
    networks:
      - admin

networks:
  admin:
    name: admin
  users:
    external:
      name: users
