version: '3.9'
services:
  backend:
    build: .
    container_name: users-microservice
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - users

  db:
    image: mysql:8
    container_name: users-db
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - users

networks:
  users:
    name: users
