version: '3.9'
services:
  users_backend:
    build: .
    ports:
      - 8001:3000
    volumes:
      - .:/app
    depends_on:
      - users_db

  users_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
